name: Playwright

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Install Dependencies
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.19.0/allure-2.19.0.zip -O allure.zip
          unzip allure.zip -d /opt/allure
          echo "/opt/allure/allure-2.19.0/bin" >> $GITHUB_PATH
        shell: bash

      - name: Generate Allure Report
        run: |
          allure generate target/allure-results -o allure-report --clean
        env:
          ALLURE_RESULTS_DIR: target/allure-results
          ALLURE_REPORT_DIR: allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Extent Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: reports/ExtentReports
